import { WordEntry } from './types';

export const DEFAULT_LETTERS = [];

export const MOCK_WORDS: WordEntry[] = [
  {
    id: 'word-terco',
    display: 'terço/terçô/terçó',
    variants: ['terço', 'terçô', 'terçó'],
    normalized: 'terco',
    length: 5,
    status: 'not-tested',
    origin: 'dictionary',
  },
  {
    id: 'word-sermo',
    display: 'sermo',
    variants: ['sermo'],
    normalized: 'sermo',
    length: 5,
    status: 'accepted',
    origin: 'dictionary',
  },
  {
    id: 'word-sorte',
    display: 'sorte',
    variants: ['sorte'],
    normalized: 'sorte',
    length: 5,
    status: 'rejected',
    origin: 'dictionary',
  },
  {
    id: 'word-termo',
    display: 'termo',
    variants: ['termo'],
    normalized: 'termo',
    length: 5,
    status: 'not-tested',
    origin: 'dictionary',
  },
  {
    id: 'word-mestre',
    display: 'mestre',
    variants: ['mestre'],
    normalized: 'mestre',
    length: 6,
    status: 'accepted',
    origin: 'dictionary',
  },
  {
    id: 'word-sebo',
    display: 'sebo',
    variants: ['sebo'],
    normalized: 'sebo',
    length: 4,
    status: 'not-tested',
    origin: 'dictionary',
  },
  {
    id: 'word-sobe',
    display: 'sobe',
    variants: ['sobe'],
    normalized: 'sobe',
    length: 4,
    status: 'rejected',
    origin: 'dictionary',
  },
  {
    id: 'word-certo',
    display: 'certo',
    variants: ['certo'],
    normalized: 'certo',
    length: 5,
    status: 'not-tested',
    origin: 'dictionary',
  },
  {
    id: 'word-morse',
    display: 'morse',
    variants: ['morse'],
    normalized: 'morse',
    length: 5,
    status: 'accepted',
    origin: 'dictionary',
  },
];
